### PR TITLE
chore: makes link to mvn central pointing to system-rules artifact

### PR DESCRIPTION
**Pull request by bartoszmajsak**

### CODE REVIEW

**Comment by stefanbirkner** [comment]
Thanks for this improvement of the Readme. Can you please change the message of your commit to "Make link to Maven Central point to system-rules" so that it is less than 50 characters. See https://chris.beams.io/posts/git-commit/

**Comment by bartoszmajsak** [comment]
Sure. I tend to use labels and don't really follow 50 chars rule, but if you do I am happy with changing that. Might be worth to add to contribution guide at some point.

**Comment by stefanbirkner** [comment]
Thanks for this contribution. I will apply the change to my other projects, too.

**Comment by bartoszmajsak** [comment]
You are welcome! That was low hanging fruit. Thanks for bunch of handy rules!

**Pull request merged**
