### PR TITLE
Add rule for modifying enviroment variables.

### PR DESCRIPTION
**Pull request by stefanbirkner**

### CODE REVIEW

**Comment by stefanbirkner** [comment]
@victornoel could you please check whether this rule fulfills your needs. Unlike your code this rule does not have a constructor that accepts a map of variables. Please tell me if you need this feature. I didn't implement it now because it adds complexity to the rule.

**Comment by victornoel** [comment]
It's great. Combined with a @Before method it would do the same, right?

Thank you :)

**Comment by victornoel** [comment]
But there is something that seems strange to me, not sure thought, originalVariables contains a reference to the original environment map, not a copy, so when set() is called, isn't the object referenced by originalVariables the map that is modified?

**Comment by stefanbirkner** [comment]
You're right. Thanks for investigating the code.

**Comment by stefanbirkner** [comment]
Merged: e778307cdcd423030a42502342b0cfcc79048655

**Pull request closed without merging**
